"use client";
import { useEffect,useState } from "react";
import { Alert,Box,Button,Card,CardContent,Dialog,DialogActions,DialogContent,DialogTitle,Grid,MenuItem,Stack,TextField,Typography } from "@mui/material";
import { AdminPageHeader } from "@/components/admin/AdminPageHeader";
import { Product,QuoteLead,SalesQuote,SalesQuoteStatus,adminManagementAPI,quoteLeadsAPI,salesQuotesAPI } from "@/lib/api-client";

const labels:Record<SalesQuoteStatus,string>={DRAFT:"Nháp",SENT:"Đã gửi",ACCEPTED:"Đã chấp nhận",REJECTED:"Từ chối",EXPIRED:"Hết hạn"};
const transitions:Record<SalesQuoteStatus,readonly SalesQuoteStatus[]>={DRAFT:["SENT"],SENT:["ACCEPTED","REJECTED","EXPIRED"],ACCEPTED:[],REJECTED:[],EXPIRED:[]};
type DraftItem={productId?:string;description:string;quantity:number;unitPrice:number};
export default function SalesQuotesPage(){
 const [rows,setRows]=useState<SalesQuote[]>([]),[leads,setLeads]=useState<QuoteLead[]>([]),[products,setProducts]=useState<Product[]>([]),[error,setError]=useState(""),[open,setOpen]=useState(false);
 const [leadId,setLeadId]=useState(""),[customerName,setCustomerName]=useState(""),[phone,setPhone]=useState(""),[company,setCompany]=useState(""),[discount,setDiscount]=useState(0),[note,setNote]=useState(""),[validUntil,setValidUntil]=useState(""),[items,setItems]=useState<DraftItem[]>([{description:"",quantity:1,unitPrice:0}]);
 const load=()=>salesQuotesAPI.getAll().then(r=>setRows(r.data)).catch(()=>setError("Không tải được báo giá."));
 useEffect(()=>{load();Promise.all([quoteLeadsAPI.getAll(),adminManagementAPI.products()]).then(([l,p])=>{setLeads(l.data);setProducts(p.data)}).catch(()=>setError("Không tải được dữ liệu tạo báo giá."));},[]);
 const chooseLead=(id:string)=>{setLeadId(id);const l=leads.find(x=>x.id===id);if(!l)return;setCustomerName(l.name);setPhone(l.phone);setCompany(l.company||"");if(l.product){const p=products.find(x=>x.id===l.product?.id);setItems([{productId:l.product.id,description:l.product.name,quantity:l.quantity||1,unitPrice:p?.sellingPrice||0}]);}};
 const product=(index:number,id:string)=>{const p=products.find(x=>x.id===id);setItems(v=>v.map((x,i)=>i===index?{...x,productId:id||undefined,description:p?.name||x.description,unitPrice:p?.sellingPrice||0}:x));};
 const change=(index:number,key:"description"|"quantity"|"unitPrice",value:string|number)=>setItems(v=>v.map((x,i)=>i===index?{...x,[key]:value}:x));
 const subtotal=items.reduce((s,x)=>s+x.quantity*x.unitPrice,0),total=Math.max(0,subtotal-discount);
 const create=async()=>{try{await salesQuotesAPI.create({leadId:leadId||undefined,customerName,phone,company:company||undefined,discount,note:note||undefined,validUntil:validUntil?new Date(validUntil).toISOString():undefined,items});setOpen(false);setLeadId("");setCustomerName("");setPhone("");setCompany("");setDiscount(0);setNote("");setValidUntil("");setItems([{description:"",quantity:1,unitPrice:0}]);load();}catch{setError("Không tạo được báo giá. Kiểm tra thông tin và đơn giá.");}};
 const status=async(id:string,value:SalesQuoteStatus)=>{try{await salesQuotesAPI.updateStatus(id,value);load();}catch{setError("Không cập nhật được trạng thái báo giá.");}};
 return <Box><AdminPageHeader title="Báo giá bán hàng" description="Tạo báo giá từ lead CRM, theo dõi gửi/chấp nhận và đồng bộ trạng thái lead." actions={<Button variant="contained" onClick={()=>setOpen(true)}>Tạo báo giá</Button>}/>
 {error&&<Alert severity="error" onClose={()=>setError("")} sx={{mb:2}}>{error}</Alert>}
 <Grid container spacing={2}>{rows.map(q=><Grid item xs={12} md={6} key={q.id}><Card><CardContent><Stack direction="row" justifyContent="space-between"><Box><Typography fontWeight={900}>{q.code}</Typography><Typography>{q.customerName} · {q.phone}</Typography>{q.company&&<Typography color="text.secondary">{q.company}</Typography>}</Box><TextField select size="small" label="Trạng thái" value={q.status} disabled={!transitions[q.status].length} onChange={e=>status(q.id,e.target.value as SalesQuoteStatus)} sx={{minWidth:150}}><MenuItem value={q.status}>{labels[q.status]}</MenuItem>{transitions[q.status].map(v=><MenuItem key={v} value={v}>{labels[v]}</MenuItem>)}</TextField></Stack>
 <Box sx={{my:1.5}}>{q.items.map(i=><Typography key={i.id} variant="body2">{i.description} × {i.quantity} — {i.lineTotal.toLocaleString("vi-VN")} ₫</Typography>)}</Box>
 <Typography>Tạm tính: {q.subtotal.toLocaleString("vi-VN")} ₫{q.discount? ` · CK: ${q.discount.toLocaleString("vi-VN")} ₫`:""}</Typography><Typography fontWeight={900}>Tổng: {q.total.toLocaleString("vi-VN")} ₫</Typography>{q.validUntil&&<Typography variant="caption">Hiệu lực đến {new Date(q.validUntil).toLocaleDateString("vi-VN")}</Typography>}</CardContent></Card></Grid>)}</Grid>
 <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="md"><DialogTitle>Tạo báo giá</DialogTitle><DialogContent><Stack spacing={2} sx={{mt:1}}><TextField select label="Từ lead CRM" value={leadId} onChange={e=>chooseLead(e.target.value)}><MenuItem value="">Không chọn lead</MenuItem>{leads.map(l=><MenuItem key={l.id} value={l.id}>{l.name} · {l.phone}{l.product?` · ${l.product.name}`:""}</MenuItem>)}</TextField><Stack direction={{xs:"column",md:"row"}} spacing={1}><TextField fullWidth label="Khách hàng" value={customerName} onChange={e=>setCustomerName(e.target.value)}/><TextField fullWidth label="Điện thoại" value={phone} onChange={e=>setPhone(e.target.value)}/><TextField fullWidth label="Công ty" value={company} onChange={e=>setCompany(e.target.value)}/></Stack>
 {items.map((item,i)=><Stack key={i} direction={{xs:"column",md:"row"}} spacing={1}><TextField select sx={{minWidth:250}} label="Sản phẩm" value={item.productId||""} onChange={e=>product(i,e.target.value)}><MenuItem value="">Nhập thủ công</MenuItem>{products.map(p=><MenuItem key={p.id} value={p.id}>{p.name} · {p.sku}</MenuItem>)}</TextField><TextField fullWidth label="Mô tả" value={item.description} onChange={e=>change(i,"description",e.target.value)}/><TextField type="number" label="SL" value={item.quantity} onChange={e=>change(i,"quantity",Number(e.target.value))} sx={{width:100}}/><TextField type="number" label="Đơn giá" value={item.unitPrice} onChange={e=>change(i,"unitPrice",Number(e.target.value))} sx={{width:180}}/><Button color="error" disabled={items.length===1} onClick={()=>setItems(v=>v.filter((_,x)=>x!==i))}>Xóa</Button></Stack>)}<Button variant="outlined" onClick={()=>setItems(v=>[...v,{description:"",quantity:1,unitPrice:0}])}>+ Dòng sản phẩm</Button>
 <Stack direction={{xs:"column",md:"row"}} spacing={1}><TextField type="number" label="Chiết khấu (₫)" value={discount} onChange={e=>setDiscount(Number(e.target.value))}/><TextField type="date" label="Hiệu lực đến" InputLabelProps={{shrink:true}} value={validUntil} onChange={e=>setValidUntil(e.target.value)}/></Stack><TextField multiline minRows={2} label="Ghi chú / điều kiện báo giá" value={note} onChange={e=>setNote(e.target.value)}/><Typography fontWeight={900}>Tổng báo giá: {total.toLocaleString("vi-VN")} ₫</Typography></Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Hủy</Button><Button variant="contained" onClick={create}>Tạo báo giá</Button></DialogActions></Dialog></Box>;
}
