const string = { type: 'string' };
const strings = { type: 'array', items: string };
export const productSchema = { type: 'object', additionalProperties: false, required: ['name','slug','shortDescription','description','highlights','specifications','applications','seo','tags','imageAltTexts','missingInformation'], properties: { name:string, slug:string, shortDescription:string, description:string, highlights:strings, specifications:{type:'array',items:{type:'object',additionalProperties:false,required:['name','value'],properties:{name:string,value:string}}}, applications:strings, seo:{type:'object',additionalProperties:false,required:['title','description','keywords'],properties:{title:string,description:string,keywords:strings}}, tags:strings, imageAltTexts:{type:'array',items:{type:'object',additionalProperties:false,required:['imageIndex','alt'],properties:{imageIndex:{type:'integer'},alt:string}}}, missingInformation:strings } };
export const blogSchema = { type:'object', additionalProperties:false, required:['title','slug','excerpt','content','tableOfContents','seo','tags','imageAltTexts','relatedProductSuggestions','missingInformation'], properties:{title:string,slug:string,excerpt:string,content:string,tableOfContents:{type:'array',items:{type:'object',additionalProperties:false,required:['title','anchor'],properties:{title:string,anchor:string}}},seo:{type:'object',additionalProperties:false,required:['title','description','primaryKeyword','secondaryKeywords'],properties:{title:string,description:string,primaryKeyword:string,secondaryKeywords:strings}},tags:strings,imageAltTexts:{type:'array',items:{type:'object',additionalProperties:false,required:['imageIndex','alt'],properties:{imageIndex:{type:'integer'},alt:string}}},relatedProductSuggestions:strings,missingInformation:strings}};
export const seoSchema = { type:'object',additionalProperties:false,required:['title','metaDescription','slug','primaryKeyword','secondaryKeywords','tags','suggestedHeadings','imageAltTexts','suggestions'],properties:{title:string,metaDescription:string,slug:string,primaryKeyword:string,secondaryKeywords:strings,tags:strings,suggestedHeadings:strings,imageAltTexts:strings,suggestions:strings}};

export function validateGenerated(value: unknown, required: string[]): boolean {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return false;
  return required.every((key) => key in (value as Record<string, unknown>));
}
