import { ProductionSeed } from './types';

const site = 'https://www.vomamxenang.com';
const guide = '/blog/chon-lop-dac-hay-lop-hoi-cho-xe-nang';
const sizeGuide = '/blog/doc-thong-so-lop-xe-nang-truoc-khi-thay';
const rimGuide = '/blog/kiem-tra-mam-xe-nang-truoc-khi-ep-lop';
// Immutable research release: searched 2026-09-09, public source evidence only.
// Scores are editorial prioritization (topic 0–45 + industry 0–30 + Vietnam 0–25), not third-party metrics.
export const initialOpportunities = [
  { domain: 'yellowpages.vn', url: 'https://www.yellowpages.vn/', name: 'Trang Vàng Việt Nam', type: 'BUSINESS_DIRECTORY', relevanceScore: 70, components: { topical: 15, industry: 30, vietnam: 25 }, evidence: 'Danh bạ công khai có ngành cơ khí, thiết bị công nghiệp và bốc xếp bằng xe nâng; có đăng ký hồ sơ miễn phí, qua ban biên tập.', target: '/', anchors: ['Võ Mâm Xe Nâng', 'Đơn vị tư vấn lốp và mâm xe nâng'], approach: 'Đăng hồ sơ doanh nghiệp thật sau khi đối chiếu tên, địa chỉ, điện thoại và ngành nghề. Chỉ dùng hồ sơ cơ bản; không mua liên kết.', supportsRegistration: true, contactUrl: 'https://www.yellowpages.vn/', note: 'Các website Trang Vàng cùng hệ thống được gộp thành một cơ hội. Chưa xác minh profile link hoặc rel.' },
  { domain: 'vla.com.vn', url: 'https://vla.com.vn/danh-ba-hoi-vien/', name: 'Hiệp hội Doanh nghiệp dịch vụ Logistics Việt Nam', type: 'ASSOCIATION', relevanceScore: 65, components: { topical: 10, industry: 30, vietnam: 25 }, evidence: 'VLA có danh bạ hội viên công khai; điều lệ nêu ngành nghề, hồ sơ và điều kiện gia nhập.', target: '/about', anchors: ['Thông tin Võ Mâm Xe Nâng'], approach: 'Trao đổi điều kiện hội viên hoặc hoạt động chuyên môn nếu phù hợp tư cách doanh nghiệp. Không gia nhập chỉ để lấy link.', contactUrl: 'https://vla.com.vn/dieu-le-hoat-dong/', note: 'Tư cách hội viên, chi phí, khả năng đặt URL và rel cần xác minh. Danh bạ không chứng minh được chấp nhận.' },
  { domain: 'huba.vn', url: 'https://huba.vn/hoi-vien/dang-ky-hoi-vien', name: 'HUBA · đăng ký hội viên', type: 'ASSOCIATION', relevanceScore: 50, components: { topical: 5, industry: 20, vietnam: 25 }, evidence: 'Trang đăng ký hội viên có biểu mẫu thông tin doanh nghiệp, lĩnh vực quan tâm và nghĩa vụ hội phí; website có danh sách hội viên doanh nghiệp.', target: '/about', anchors: ['Võ Mâm Xe Nâng'], approach: 'Kiểm tra tư cách hội viên và giá trị kết nối doanh nghiệp tại TP.HCM. Hỏi về hồ sơ công khai nếu tham gia có lý do kinh doanh thật.', supportsRegistration: true, contactUrl: 'https://huba.vn/hoi-vien/dang-ky-hoi-vien/', note: 'Thông tin hội phí trên biểu mẫu có thể cũ; xác nhận với HUBA. Chưa xác minh liên kết ngoài.' },
  { domain: 'vlr.vn', url: 'https://vlr.vn/', name: 'Vietnam Logistics Review', type: 'NEWS', relevanceScore: 75, components: { topical: 20, industry: 30, vietnam: 25 }, evidence: 'Website đăng nội dung logistics, chuỗi cung ứng và công nghệ; có thông tin liên hệ công khai cuối trang.', target: guide, anchors: ['Hướng dẫn chọn lốp theo điều kiện vận hành', 'Lốp đặc và lốp hơi xe nâng'], approach: 'Đề xuất góc nhìn thực tế về bảo trì bánh xe trong kho, kèm ảnh và số liệu công việc đã được khách hàng cho phép. Hỏi ban biên tập trước khi chuẩn bị bài.', contactUrl: 'https://vlr.vn/', note: 'Có liên hệ không đồng nghĩa nhận guest post. Chưa xác minh chính sách dẫn nguồn hoặc rel.' },
  { domain: 'techport.vn', url: 'https://techport.vn/', name: 'Sàn Giao dịch Công nghệ TP.HCM', type: 'B2B_MARKETPLACE', relevanceScore: 70, components: { topical: 15, industry: 30, vietnam: 25 }, evidence: 'Trang chủ có mục thiết bị chào bán, nhà cung ứng, yêu cầu tìm mua và kết nối cung cầu công nghệ.', target: '/products/dich-vu-thay-lop-ep-mam-xe-nang', anchors: ['Dịch vụ khảo sát và thay lốp xe nâng'], approach: 'Hỏi sàn về điều kiện giới thiệu dịch vụ kỹ thuật/thiết bị phù hợp. Chuẩn bị hồ sơ năng lực và thông số thực tế; chỉ đăng khi sàn xác nhận phù hợp.', contactUrl: 'https://techport.vn/', note: 'Sàn tập trung công nghệ; không mặc định mọi sản phẩm lốp được chấp nhận. Chưa xác minh đăng ký và URL ngoài.' },
  { domain: 'hatex.vn', url: 'https://www.hatex.vn/huong-dan/cach-dang-san-pham-tren-hatexvn-cho-nguoi-moi-bat-dau.html', name: 'Hatex · hướng dẫn gian hàng', type: 'B2B_MARKETPLACE', relevanceScore: 70, components: { topical: 15, industry: 30, vietnam: 25 }, evidence: 'Hướng dẫn công khai mô tả đăng ký thành viên, thiết lập gian hàng và đăng sản phẩm.', target: '/products/lop-dac-xe-nang-6-00-9-cho-kho-xuong', anchors: ['Lốp đặc xe nâng 6.00-9', 'Thông tin sản phẩm và đối chiếu mâm'], approach: 'Kiểm tra lại hướng dẫn và điều khoản hiện hành; đăng đúng sản phẩm hiện có nếu phù hợp danh mục của sàn.', supportsRegistration: true, supportsPosting: true, contactUrl: 'https://www.hatex.vn/', note: 'Bằng chứng từ kết quả tìm kiếm có crawl gần đây; mở trực tiếp bằng công cụ web bị lỗi. Cần kiểm tra thủ công trước khi duyệt; hướng dẫn xuất bản nhiều năm trước.' },
  { domain: 'forkliftaction.com', url: 'https://www.forkliftaction.com/forum/how-to-decide-on-the-best-tyre-for-your-forklift.aspx?q=136418', name: 'Forkliftaction · thảo luận chọn lốp', type: 'FORUM', relevanceScore: 75, components: { topical: 45, industry: 30, vietnam: 0 }, evidence: 'Có thảo luận chuyên về lựa chọn lốp xe nâng trong mục Safety & Training, bài hiển thị ngày 18/06/2024. Website có chức năng đăng thảo luận/trả lời.', target: guide, anchors: ['Solid versus pneumatic selection guide', 'Practical tire selection checklist'], approach: 'Đọc quy tắc diễn đàn; trả lời kỹ thuật có ích trong thảo luận còn hoạt động. Chỉ dẫn nguồn nếu giúp người đọc, không khơi lại bài cũ để quảng cáo.', supportsPosting: true, contactUrl: 'https://www.forkliftaction.com/', note: 'Ngày của thảo luận đã thấy không phải ngày hoạt động mới nhất toàn forum. Cần bản tiếng Anh được duyệt; rel và external-link policy UNKNOWN.', forum: { section: 'Safety & Training', observedDiscussionDate: '2024-06-18', lastActiveDate: null, externalLinkPolicy: 'UNKNOWN', rel: 'UNKNOWN' } },
  { domain: 'forkliftaction.com', url: 'https://www.forkliftaction.com/news/editorial-calendar.aspx', name: 'Forkliftaction · đóng góp chuyên gia', type: 'GUEST_POST', relevanceScore: 75, components: { topical: 45, industry: 30, vietnam: 0 }, evidence: 'Lịch biên tập mời người có chuyên môn hỏi cách đóng góp cho các chuyên đề, gồm giải pháp an toàn và quản lý đội xe.', target: rimGuide, anchors: ['Wheel and rim inspection checklist', 'Forklift rim inspection before fitting'], approach: 'Đề xuất checklist kiểm tra mâm có ảnh công việc thực tế để biên tập đánh giá. Hỏi phạm vi chuyên đề và chính sách trích dẫn; không đề nghị mua link.', supportsGuestPost: true, contactUrl: 'https://www.forkliftaction.com/news/editorial-calendar.aspx', note: 'Lời mời đóng góp chuyên gia không bảo đảm được xuất bản hoặc có backlink. Cần bản tiếng Anh và xác minh kỹ thuật.' },
  { domain: 'logisticsbusiness.com', url: 'https://logisticsbusiness.com/media-kit', name: 'Logistics Business · editorial enquiries', type: 'NEWS', relevanceScore: 60, components: { topical: 30, industry: 30, vietnam: 0 }, evidence: 'Trang media kit phân biệt liên hệ biên tập với quảng cáo; chủ đề biên tập được chọn theo diễn biến ngành.', target: guide, anchors: ['Forklift tire selection by operating conditions'], approach: 'Gửi đề xuất biên tập về điều kiện nền kho và lựa chọn lốp, sử dụng bằng chứng vận hành được xác minh. Không chọn gói quảng cáo để mua backlink.', contactUrl: 'https://logisticsbusiness.com/media-kit/', note: 'Email hiện bị che trong bản đọc; không suy đoán địa chỉ. Khả năng nhận bài ngoài và rel chưa xác minh.' },
  { domain: 'dcvelocity.com', url: 'https://www.dcvelocity.com/contact/staff', name: 'DC Velocity · editorial staff', type: 'NEWS', relevanceScore: 60, components: { topical: 30, industry: 30, vietnam: 0 }, evidence: 'Trang liên hệ công khai liệt kê bộ phận biên tập của ấn phẩm về logistics và hoạt động phân phối.', target: sizeGuide, anchors: ['Forklift tire size identification guide'], approach: 'Hỏi biên tập viên phù hợp về bài hướng dẫn nhận diện thông số và giới hạn tương thích, kèm nguồn từ nhà sản xuất. Chỉ gửi bản nháp sau khi có phản hồi.', contactUrl: 'https://www.dcvelocity.com/contact/staff', note: 'Danh sách biên tập không chứng minh nhận guest post hoặc cho link; cần duyệt thủ công.' },
];
export const seoOpportunitiesSeed: ProductionSeed = {
  key: '009-seo-opportunities', name: 'Evidence-backed SEO opportunity research (2026-09-09)', preview: { productsToCreate: 0 },
  async run(db) {
    if (!db.backlinkOpportunity) throw new Error('SEO migration/client required before seed 009');
    for (const entry of initialOpportunities) {
      const data = { domain: entry.domain, url: entry.url, name: entry.name, type: entry.type, relevanceScore: entry.relevanceScore, evidence: entry.evidence, evidenceUrl: entry.url, suggestedTargetUrl: site + entry.target, suggestedAnchorTexts: entry.anchors, suggestedApproach: entry.approach, notes: entry.note, supportsRegistration: entry.supportsRegistration ?? null, supportsPosting: entry.supportsPosting ?? null, supportsGuestPost: entry.supportsGuestPost ?? null, contactUrl: entry.contactUrl, status: 'DISCOVERED', risk: 'UNKNOWN', requiresManualReview: true, discoveredAt: new Date('2026-09-09T03:00:00Z'), lastCheckedAt: new Date('2026-09-09T03:00:00Z'), details: { researchBatch: '2026-09-09-v3', evidenceMethod: 'Current public web search and source-page inspection; see notes for access limits', scoreMethod: 'Editorial topical priority: topical 0–45, industry 0–30, Vietnam 0–25; not DA/DR', components: entry.components, externalLinkPolicy: 'UNKNOWN', rel: 'UNKNOWN', lastActiveDate: null, authority: 'UNKNOWN', traffic: 'UNKNOWN', spamScore: 'UNKNOWN', indexability: 'UNKNOWN', ...(entry.forum ? { forum: { ...entry.forum, discussionExamples: [entry.url] } } : {}) } };
      await db.backlinkOpportunity.upsert({ where: { domain_url: { domain: entry.domain, url: entry.url } }, create: data, update: {} });
    }
  },
};
