"use client";

import { Alert, Box, Card, CardContent, CircularProgress, Grid, Typography } from "@mui/material";
import { useEffect, useState } from "react";
import { AdminPageHeader } from "@/components/admin/AdminPageHeader";
import { StatCard } from "@/components/admin/StatCard";
import { adminManagementAPI } from "@/lib/api-client";
import { conversionAnalyticsAPI } from "@/lib/conversion-analytics";

export default function ReportsPage() { const [conversion,setConversion]=useState<{events:Record<string,number>;leads:Record<string,number>;topPaths:{path:string;count:number}[]}>(); const [data, setData] = useState<Awaited<ReturnType<typeof adminManagementAPI.reports>>["data"]>(); const [error, setError] = useState(false); useEffect(() => { Promise.all([adminManagementAPI.reports(),conversionAnalyticsAPI.report()]).then(([response,conv])=>{setData(response.data);setConversion(conv.data)}).catch(() => setError(true)); }, []); if (error) return <Alert severity="error">Không thể tải báo cáo.</Alert>; if (!data) return <CircularProgress />; return <Box><AdminPageHeader title="Báo cáo & thống kê" description="Chỉ tính đơn hàng đã thanh toán" /><Grid container spacing={2}><Grid item xs={12} sm={6} md={3}><StatCard label="Doanh thu" value={`${data.revenue.toLocaleString("vi-VN")} ₫`} icon="₫" /></Grid><Grid item xs={12} sm={6} md={3}><StatCard label="Đơn đã thanh toán" value={data.paidOrders} icon="✓" /></Grid><Grid item xs={12} sm={6} md={3}><StatCard label="Giá trị đơn TB" value={`${data.averageOrderValue.toLocaleString("vi-VN")} ₫`} icon="₫" /></Grid><Grid item xs={12} sm={6} md={3}><StatCard label="Giá trị tồn kho" value={`${data.inventoryCost.toLocaleString("vi-VN")} ₫`} icon="₫" /></Grid><Grid item xs={12}><Card><CardContent><Typography variant="h6" gutterBottom>Khách hàng doanh thu cao</Typography>{data.topClients.map((client) => <Typography key={client.id}>{client.name} — {client.orders} đơn — {client.revenue.toLocaleString("vi-VN")} ₫</Typography>)}</CardContent></Card></Grid><Grid item xs={12}><Card><CardContent><Typography variant="h6" gutterBottom>Conversion website</Typography>{conversion&&<Grid container spacing={2}><Grid item xs={6} md={2}><b>Call</b><Typography>{conversion.events.CLICK_PHONE||0}</Typography></Grid><Grid item xs={6} md={2}><b>Zalo</b><Typography>{conversion.events.CLICK_ZALO||0}</Typography></Grid><Grid item xs={6} md={2}><b>Mở báo giá</b><Typography>{conversion.events.OPEN_QUOTE||0}</Typography></Grid><Grid item xs={6} md={2}><b>Gửi báo giá</b><Typography>{conversion.events.SUBMIT_QUOTE||0}</Typography></Grid><Grid item xs={6} md={2}><b>Lead WON</b><Typography>{conversion.leads.WON||0}</Typography></Grid></Grid>}</CardContent></Card></Grid></Grid></Box>; }
